---
# vim:ff=unix ts=2 sw=2 ai expandtab

- name: Provision a django server
  hosts: django
  remote_user: ubuntu
  vars:
    - home: "/home/{{ user }}"
    - app_path: "{{ home }}/git/{{ site_name }}"
    - virtualenv: "{{ home }}/env/{{ site_name }}"
  tasks:

    - name: create project dirs
      file:
        state: directory
        path: "{{ item }}/{{ site_name }}"
      with_items:
        - log
        - static
        - media

    - name: git clone django repo
      git:
        repo: "{{ git_repo }}"
        version: "{{ git_branch }}"
        dest: "{{ app_path }}"
        accept_hostkey: yes

    - name: create virtualenv and install requirements
      pip:
        virtualenv_python: python3
        virtualenv: "{{ virtualenv }}"
        requirements: "{{ app_path }}/requirements.txt"

    - name: django migrate
      django_manage:
        command: migrate --fake-initial
        app_path: "{{ app_path }}"
        settings: "{{ settings }}"
        virtualenv: "{{ virtualenv }}"

    - name: django collectstatic
      django_manage:
        command: collectstatic --no-input
        app_path: "{{ app_path }}"
        settings: "{{ settings }}"
        virtualenv: "{{ virtualenv }}"

    - name: chown home
      become: true
      file:
        state: directory
        recurse: yes
        path: "{{ home }}"
        owner: "{{ user }}"
        group: "{{ user }}"

    - name: render supervisor conf
      become: true
      template:
        src: "../templates/supervisor_app.conf"
        dest: "/etc/supervisor/conf.d/{{ site_name }}.conf"

    - name: supervisorctl update
      become: true
      command: "supervisorctl update"

    - name: supervisorctl restart site
      become: true
      command: "supervisorctl restart {{ site_name }}:"

    - name: render nginx conf
      become: true
      template:
        src: "../templates/nginx_gunicorn.conf"
        dest: "/etc/nginx/conf.d/{{ site_name }}.conf"

    - name: restart nginx service
      become: true
      service:
        name: nginx
        state: restarted
        enabled: yes
