---
# vim:ff=unix ts=2 sw=2 ai expandtab

- name: Provision a postgresql server
  hosts: postgresql
  remote_user: ubuntu
  tasks:
    - name: install postgresql
      become: true
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - postgresql
        - postgresql-contrib
