---
# vim:ff=unix ts=2 sw=2 ai expandtab

- name: Provision a postgresql server
  hosts: postgresql
  remote_user: root
  become: yes
  become_user: postgres
  tasks:

    - name: create postgresql user
      postgresql_user:
        name: "{{ user }}"

    - name: create postgresql db
      postgresql_db:
        name: "{{ site_name }}"
        owner: "{{ user }}"

  handlers:
    - name: restart postgresql
      become: true
      service:
        name: postgresql
        state: restarted
        enabled: yes
