---
# vim:ff=unix ts=2 sw=2 ai expandtab


# common setup for a ubuntu server
# should not contain any project info
- name: Provision a ubuntu server
  hosts: ubuntu
  remote_user: "{{ user }}"
  tasks:

    - name: install debian packages
      become: true
      apt:
        name: "{{ item }}"
        state: latest
        update_cache: yes
      with_items:
        - python-pip
        - python3-dev
        - virtualenv
        - virtualenvwrapper
        - silversearcher-ag
        - htop
        - tmux
        - tree
        - supervisor
        - git
        - zsh
        - vim

    - name: start supervisor service
      service:
        name: supervisor
        state: started
        enabled: yes

    - name: git config alias
      git_config:
        scope: system
        name: "{{ item.name }}"
        value:  "{{ item.value }}"
      with_items:
        - { name: "alias.br", value: "branch"}
        - { name: "alias.co", value: "checkout"}
        - { name: "alias.ci", value: "commit"}
        - { name: "alias.st", value: "status"}
        - { name: "color.ui", value: "true"}

    - name: change shell to zsh
      become: true
      user:
        name: "{{ user }}"
        shell: /usr/bin/zsh
        generate_ssh_key: yes
        ssh_key_comment: "{{ user }}@{{ site_name }}"

    - name: git clone oh-my-zsh
      git:
        repo: git://github.com/robbyrussell/oh-my-zsh.git
        dest: ~/.oh-my-zsh
        accept_hostkey: yes

    - name: copy oh-my-zsh zshrc
      copy:
        remote_src: True
        src: ~/.oh-my-zsh/templates/zshrc.zsh-template
        dest: ~/.zshrc
        force: no

    - name: change oh-my-zsh theme
      lineinfile:
        dest: ~/.zshrc
        regexp: "^ZSH_THEME"
        line: 'ZSH_THEME="zhann"'

    - name: create dirs
      file:
        state: directory
        path: "~/{{ item }}"
      with_items:
        - git
        - env
        - log
        - static
        - media
